blank_issues_enabled: false
contact_links:
  - name: Important Notice
    url: https://github.com/usabarashi/pycategory/issues/new?template=bug_report.md
    about: This project only accepts bug reports. Feature requests and questions are not accepted at this time. Please use the Bug Report template for reporting bugs only.
